# Datasource (Docker Postgres)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=admin
quarkus.datasource.password=adminpassword
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/crypto_platform

# Hibernate (ORM)
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

# OpenAPI (Swagger UI para el tribunal)
quarkus.swagger-ui.always-include=true
