quarkus.http.port=8080

quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,OPTIONS,PUT,DELETE
quarkus.http.cors.headers=Content-Type,Authorization,Accept,Origin

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=admin
quarkus.datasource.password=adminpassword
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/crypto_platform
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

quarkus.swagger-ui.always-include=true

mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=https://crypto-ai-platform.com
smallrye.jwt.sign.key.location=privateKey.pem
quarkus.native.resources.includes=privateKey.pem,publicKey.pem
smallrye.jwt.new-token.lifespan=3600