quarkus.http.port=8081

quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization

binance.api.url=https://api.binance.com
quarkus.swagger-ui.always-include=true